# config file for r/place plugin

# all allowed Blocks to place
allowedBlocks:
- AIR
- MYCELIUM
- STONE
- GRANITE
- POLISHED_GRANITE
- DIORITE
- POLISHED_DIORITE
- ANDESITE
- POLISHED_ANDESITE
- DEEPSLATE
- COBBLED_DEEPSLATE
- POLISHED_DEEPSLATE
- CALCITE
- TUFF
- CHISELED_TUFF
- POLISHED_TUFF
- POLISHED_TUFF_WALL
- TUFF_BRICKS
- CHISELED_TUFF_BRICKS
- DRIPSTONE_BLOCK
- GRASS_BLOCK
- DIRT
- COARSE_DIRT
- PODZOL
- ROOTED_DIRT
- MUD
- CRIMSON_NYLIUM
- WARPED_NYLIUM
- COBBLESTONE
- OAK_PLANKS
- SPRUCE_PLANKS
- BIRCH_PLANKS
- JUNGLE_PLANKS
- ACACIA_PLANKS
- CHERRY_PLANKS
- DARK_OAK_PLANKS
- MANGROVE_PLANKS
- BAMBOO_PLANKS
- CRIMSON_PLANKS
- WARPED_PLANKS
- BAMBOO_MOSAIC
- SAND
- SUSPICIOUS_SAND
- SUSPICIOUS_GRAVEL
- RED_SAND
- GRAVEL
- COAL_ORE
- DEEPSLATE_COAL_ORE
- IRON_ORE
- DEEPSLATE_IRON_ORE
- COPPER_ORE
- DEEPSLATE_COPPER_ORE
- GOLD_ORE
- DEEPSLATE_GOLD_ORE
- REDSTONE_ORE
- DEEPSLATE_REDSTONE_ORE
- EMERALD_ORE
- DEEPSLATE_EMERALD_ORE
- LAPIS_ORE
- DEEPSLATE_LAPIS_ORE
- DIAMOND_ORE
- DEEPSLATE_DIAMOND_ORE
- NETHER_GOLD_ORE
- NETHER_QUARTZ_ORE
- ANCIENT_DEBRIS
- COAL_BLOCK
- RAW_IRON_BLOCK
- RAW_COPPER_BLOCK
- RAW_GOLD_BLOCK
- AMETHYST_BLOCK
- BUDDING_AMETHYST
- IRON_BLOCK
- COPPER_BLOCK
- GOLD_BLOCK
- DIAMOND_BLOCK
- NETHERITE_BLOCK
- EXPOSED_COPPER
- WEATHERED_COPPER
- OXIDIZED_COPPER
- CHISELED_COPPER
- EXPOSED_CHISELED_COPPER
- WEATHERED_CHISELED_COPPER
- OXIDIZED_CHISELED_COPPER
- CUT_COPPER
- EXPOSED_CUT_COPPER
- WEATHERED_CUT_COPPER
- OXIDIZED_CUT_COPPER
- WAXED_COPPER_BLOCK
- WAXED_EXPOSED_COPPER
- WAXED_WEATHERED_COPPER
- WAXED_OXIDIZED_COPPER
- WAXED_CHISELED_COPPER
- WAXED_EXPOSED_CHISELED_COPPER
- WAXED_WEATHERED_CHISELED_COPPER
- WAXED_OXIDIZED_CHISELED_COPPER
- WAXED_CUT_COPPER
- WAXED_EXPOSED_CUT_COPPER
- WAXED_WEATHERED_CUT_COPPER
- WAXED_OXIDIZED_CUT_COPPER
- OAK_LOG
- SPRUCE_LOG
- BIRCH_LOG
- JUNGLE_LOG
- ACACIA_LOG
- CHERRY_LOG
- DARK_OAK_LOG
- MANGROVE_LOG
- MANGROVE_ROOTS
- MUDDY_MANGROVE_ROOTS
- CRIMSON_STEM
- WARPED_STEM
- BAMBOO_BLOCK
- STRIPPED_OAK_LOG
- STRIPPED_SPRUCE_LOG
- STRIPPED_BIRCH_LOG
- STRIPPED_JUNGLE_LOG
- STRIPPED_ACACIA_LOG
- STRIPPED_CHERRY_LOG
- STRIPPED_DARK_OAK_LOG
- STRIPPED_MANGROVE_LOG
- STRIPPED_CRIMSON_STEM
- STRIPPED_WARPED_STEM
- STRIPPED_OAK_WOOD
- STRIPPED_SPRUCE_WOOD
- STRIPPED_BIRCH_WOOD
- STRIPPED_JUNGLE_WOOD
- STRIPPED_ACACIA_WOOD
- STRIPPED_CHERRY_WOOD
- STRIPPED_DARK_OAK_WOOD
- STRIPPED_MANGROVE_WOOD
- STRIPPED_CRIMSON_HYPHAE
- STRIPPED_WARPED_HYPHAE
- STRIPPED_BAMBOO_BLOCK
- OAK_WOOD
- SPRUCE_WOOD
- BIRCH_WOOD
- JUNGLE_WOOD
- ACACIA_WOOD
- CHERRY_WOOD
- DARK_OAK_WOOD
- MANGROVE_WOOD
- CRIMSON_HYPHAE
- WARPED_HYPHAE
- OAK_LEAVES
- SPRUCE_LEAVES
- BIRCH_LEAVES
- JUNGLE_LEAVES
- ACACIA_LEAVES
- CHERRY_LEAVES
- DARK_OAK_LEAVES
- MANGROVE_LEAVES
- AZALEA_LEAVES
- FLOWERING_AZALEA_LEAVES
- SPONGE
- WET_SPONGE
- GLASS
- TINTED_GLASS
- LAPIS_BLOCK
- SANDSTONE
- CHISELED_SANDSTONE
- CUT_SANDSTONE
- WHITE_WOOL
- ORANGE_WOOL
- MAGENTA_WOOL
- LIGHT_BLUE_WOOL
- YELLOW_WOOL
- LIME_WOOL
- PINK_WOOL
- GRAY_WOOL
- LIGHT_GRAY_WOOL
- CYAN_WOOL
- PURPLE_WOOL
- BLUE_WOOL
- BROWN_WOOL
- GREEN_WOOL
- RED_WOOL
- BLACK_WOOL
- SMOOTH_QUARTZ
- SMOOTH_RED_SANDSTONE
- SMOOTH_SANDSTONE
- SMOOTH_STONE
- BRICKS
- BOOKSHELF
- CHISELED_BOOKSHELF
- DECORATED_POT
- MOSSY_COBBLESTONE
- OBSIDIAN
- PURPUR_BLOCK
- PURPUR_PILLAR
- CRAFTING_TABLE
- FURNACE
- ICE
- SNOW_BLOCK
- CLAY
- JUKEBOX
- PUMPKIN
- CARVED_PUMPKIN
- JACK_O_LANTERN
- NETHERRACK
- SOUL_SAND
- SOUL_SOIL
- BASALT
- POLISHED_BASALT
- SMOOTH_BASALT
- GLOWSTONE
- STONE_BRICKS
- MOSSY_STONE_BRICKS
- CRACKED_STONE_BRICKS
- CHISELED_STONE_BRICKS
- PACKED_MUD
- MUD_BRICKS
- DEEPSLATE_BRICKS
- CRACKED_DEEPSLATE_BRICKS
- DEEPSLATE_TILES
- CRACKED_DEEPSLATE_TILES
- CHISELED_DEEPSLATE
- REINFORCED_DEEPSLATE
- BROWN_MUSHROOM_BLOCK
- RED_MUSHROOM_BLOCK
- MUSHROOM_STEM
- GLASS_PANE
- NETHER_BRICKS
- CRACKED_NETHER_BRICKS
- CHISELED_NETHER_BRICKS
- SCULK
- SCULK_CATALYST
- END_STONE
- END_STONE_BRICKS
- EMERALD_BLOCK
- BEACON
- CHISELED_QUARTZ_BLOCK
- QUARTZ_BLOCK
- QUARTZ_BRICKS
- QUARTZ_PILLAR
- WHITE_TERRACOTTA
- ORANGE_TERRACOTTA
- MAGENTA_TERRACOTTA
- LIGHT_BLUE_TERRACOTTA
- YELLOW_TERRACOTTA
- LIME_TERRACOTTA
- PINK_TERRACOTTA
- GRAY_TERRACOTTA
- LIGHT_GRAY_TERRACOTTA
- CYAN_TERRACOTTA
- PURPLE_TERRACOTTA
- BLUE_TERRACOTTA
- BROWN_TERRACOTTA
- GREEN_TERRACOTTA
- RED_TERRACOTTA
- BLACK_TERRACOTTA
- HAY_BLOCK
- TERRACOTTA
- PACKED_ICE
- DIRT_PATH
- WHITE_STAINED_GLASS
- ORANGE_STAINED_GLASS
- MAGENTA_STAINED_GLASS
- LIGHT_BLUE_STAINED_GLASS
- YELLOW_STAINED_GLASS
- LIME_STAINED_GLASS
- PINK_STAINED_GLASS
- GRAY_STAINED_GLASS
- LIGHT_GRAY_STAINED_GLASS
- CYAN_STAINED_GLASS
- PURPLE_STAINED_GLASS
- BLUE_STAINED_GLASS
- BROWN_STAINED_GLASS
- GREEN_STAINED_GLASS
- RED_STAINED_GLASS
- BLACK_STAINED_GLASS
- WHITE_STAINED_GLASS_PANE
- ORANGE_STAINED_GLASS_PANE
- MAGENTA_STAINED_GLASS_PANE
- LIGHT_BLUE_STAINED_GLASS_PANE
- YELLOW_STAINED_GLASS_PANE
- LIME_STAINED_GLASS_PANE
- PINK_STAINED_GLASS_PANE
- GRAY_STAINED_GLASS_PANE
- LIGHT_GRAY_STAINED_GLASS_PANE
- CYAN_STAINED_GLASS_PANE
- PURPLE_STAINED_GLASS_PANE
- BLUE_STAINED_GLASS_PANE
- BROWN_STAINED_GLASS_PANE
- GREEN_STAINED_GLASS_PANE
- RED_STAINED_GLASS_PANE
- BLACK_STAINED_GLASS_PANE
- PRISMARINE
- PRISMARINE_BRICKS
- DARK_PRISMARINE
- SEA_LANTERN
- RED_SANDSTONE
- CHISELED_RED_SANDSTONE
- CUT_RED_SANDSTONE
- MAGMA_BLOCK
- NETHER_WART_BLOCK
- WARPED_WART_BLOCK
- RED_NETHER_BRICKS
- BONE_BLOCK
- SHULKER_BOX
- WHITE_SHULKER_BOX
- ORANGE_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- YELLOW_SHULKER_BOX
- LIME_SHULKER_BOX
- PINK_SHULKER_BOX
- GRAY_SHULKER_BOX
- LIGHT_GRAY_SHULKER_BOX
- CYAN_SHULKER_BOX
- PURPLE_SHULKER_BOX
- BLUE_SHULKER_BOX
- BROWN_SHULKER_BOX
- GREEN_SHULKER_BOX
- RED_SHULKER_BOX
- BLACK_SHULKER_BOX
- WHITE_GLAZED_TERRACOTTA
- ORANGE_GLAZED_TERRACOTTA
- MAGENTA_GLAZED_TERRACOTTA
- LIGHT_BLUE_GLAZED_TERRACOTTA
- YELLOW_GLAZED_TERRACOTTA
- LIME_GLAZED_TERRACOTTA
- PINK_GLAZED_TERRACOTTA
- GRAY_GLAZED_TERRACOTTA
- LIGHT_GRAY_GLAZED_TERRACOTTA
- CYAN_GLAZED_TERRACOTTA
- PURPLE_GLAZED_TERRACOTTA
- BLUE_GLAZED_TERRACOTTA
- BROWN_GLAZED_TERRACOTTA
- GREEN_GLAZED_TERRACOTTA
- RED_GLAZED_TERRACOTTA
- BLACK_GLAZED_TERRACOTTA
- WHITE_CONCRETE
- ORANGE_CONCRETE
- MAGENTA_CONCRETE
- LIGHT_BLUE_CONCRETE
- YELLOW_CONCRETE
- LIME_CONCRETE
- PINK_CONCRETE
- GRAY_CONCRETE
- LIGHT_GRAY_CONCRETE
- CYAN_CONCRETE
- PURPLE_CONCRETE
- BLUE_CONCRETE
- BROWN_CONCRETE
- GREEN_CONCRETE
- RED_CONCRETE
- BLACK_CONCRETE
- WHITE_CONCRETE_POWDER
- ORANGE_CONCRETE_POWDER
- MAGENTA_CONCRETE_POWDER
- LIGHT_BLUE_CONCRETE_POWDER
- YELLOW_CONCRETE_POWDER
- LIME_CONCRETE_POWDER
- PINK_CONCRETE_POWDER
- GRAY_CONCRETE_POWDER
- LIGHT_GRAY_CONCRETE_POWDER
- CYAN_CONCRETE_POWDER
- PURPLE_CONCRETE_POWDER
- BLUE_CONCRETE_POWDER
- BROWN_CONCRETE_POWDER
- GREEN_CONCRETE_POWDER
- RED_CONCRETE_POWDER
- BLACK_CONCRETE_POWDER
- DEAD_TUBE_CORAL_BLOCK
- DEAD_BRAIN_CORAL_BLOCK
- DEAD_BUBBLE_CORAL_BLOCK
- DEAD_FIRE_CORAL_BLOCK
- DEAD_HORN_CORAL_BLOCK
- TUBE_CORAL_BLOCK
- BRAIN_CORAL_BLOCK
- BUBBLE_CORAL_BLOCK
- FIRE_CORAL_BLOCK
- HORN_CORAL_BLOCK
- BLUE_ICE
- SCAFFOLDING
- REDSTONE_BLOCK
- PISTON
- STICKY_PISTON
- SLIME_BLOCK
- HONEY_BLOCK
- OBSERVER
- HOPPER
- DISPENSER
- DROPPER
- TARGET
- TNT
- BRICK
- BEEHIVE
- HONEYCOMB_BLOCK
- LODESTONE
- CRYING_OBSIDIAN
- BLACKSTONE
- GILDED_BLACKSTONE
- POLISHED_BLACKSTONE
- CHISELED_POLISHED_BLACKSTONE
- POLISHED_BLACKSTONE_BRICKS
- CRACKED_POLISHED_BLACKSTONE_BRICKS
- OCHRE_FROGLIGHT
- VERDANT_FROGLIGHT
- PEARLESCENT_FROGLIGHT
- COPPER_GRATE
- EXPOSED_COPPER_GRATE
- WEATHERED_COPPER_GRATE
- OXIDIZED_COPPER_GRATE
- WAXED_COPPER_GRATE
- WAXED_EXPOSED_COPPER_GRATE
- WAXED_WEATHERED_COPPER_GRATE
- WAXED_OXIDIZED_COPPER_GRATE
- COPPER_BULB
- EXPOSED_COPPER_BULB
- WEATHERED_COPPER_BULB
- OXIDIZED_COPPER_BULB
- WAXED_COPPER_BULB
- WAXED_EXPOSED_COPPER_BULB
- WAXED_WEATHERED_COPPER_BULB
- WAXED_OXIDIZED_COPPER_BULB